### PR TITLE
Drop Python 2 support

### LINKED ISSUE #221: Drop Python 2 support
[I dropped Python 2 support downstream in the Debian package earlier today.](https://tracker.debian.org/news/1071586/accepted-mwparserfromhell-054-2-source-into-unstable/)

We should drop support for Python 2 on/before the clock runs out: https://pythonclock.org/

### PR DESCRIPTION
**Pull request by legoktm**
Fixes #221.

### CODE REVIEW

**Comment by earwig** [comment]
Does pywikibot still support Python 2? If so, do we need to wait for them to drop it first?

**Comment by legoktm** [comment]
> Does pywikibot still support Python 2?

Yes, but only for a few more months (c.f. [phab](https://phabricator.wikimedia.org/T213287)).

> If so, do we need to wait for them to drop it first?

I'd say no, for two reasons.
1. mwparserfromhell is optional for the core library with a regex fallback. The only script that actually requires it is patrol.py.
2. If we set [python_requires](https://packaging.python.org/guides/distributing-packages-using-setuptools/#python-requires) in setup.py, pip should automatically install the latest Python 2-compatible version of mwph.

**Comment by earwig** [comment]
Okay, I'm satisfied with that reasoning. v0.6 can be our first py3-only release (and I'm sure it will take at least a couple more weeks to iron everything out given the recent flurry of activity).

Apologies, but could you rebase on top of the most recent commit to move the SmartList?

**Comment by legoktm** [comment]
Rebased.

**Pull request merged**
