### PR TITLE
Some fixes for the parsing of external links

### PR DESCRIPTION
**Pull request by lahwaacz**
I think this would fix the problem reported in #197, please let me know if there are any problems with this approach.

Also, how can I port this to the C tokenizer? The condition there is
```c
if (Py_UNICODE_ISSPACE(chunk) || is_marker(chunk))
```
and I don't know how to use the `re` module or its equivalent from C Python.

### CODE REVIEW

**Comment by lahwaacz** [comment]
I've attempted to port the fix to the C tokenizer, please let me know if it's OK.

I also noticed that `re.fullmatch` does not exist in Python 2, but I don't think that will be a problem in 2020...

**Comment by lahwaacz** [comment]
I've rebased my changes on the current develop branch, but now [Appveyor checks for Python 3.4](https://ci.appveyor.com/project/earwig/mwparserfromhell/builds/30067815/job/x0h3eu9j7qrqrjnr) fail and I have no idea what is the problem:
```
mwparserfromhell/parser/ctokenizer\tok_parse.c(591) : error C2143: syntax error : missing ';' before 'type'
mwparserfromhell/parser/ctokenizer\tok_parse.c(592) : error C2065: 'is_non_word' : undeclared identifier
mwparserfromhell/parser/ctokenizer\tok_parse.c(596) : error C2065: 'is_non_word' : undeclared identifier
```

Also note that there is a warning due to `python_requires` from #234:

    C:\Python34-x64\lib\distutils\dist.py:260: UserWarning: Unknown distribution option: 'python_requires'
      warnings.warn(msg)

**Comment by lahwaacz** [comment]
@earwig I've rebased on the just released version 0.6 and the Appveyor build failure is gone. Please let me know how it looks!

**Comment by earwig** [comment]
Thanks!

Good catch with the uppercase URL schemes. My wikitext editor gets this wrong, but yep, it's valid in MediaWiki...

I would prefer to do this without re.fullmatch in the C tokenizer since all we're using it for is to check whether the characters are alphanumeric. However, we can leave that for a separate change.

**Pull request merged**
