### PR TITLE
rewrite and extend Caveats

### PR DESCRIPTION
**Pull request by Larivact**
"inherent limitation in wikicode" sounds misleading it's about generating an AST instead of HTML. #179

### CODE REVIEW

**Comment by earwig** [comment]
This is good, but I would broaden the scope of the second bullet to mention other cases where template-sensitive information is unavailable. For example, if I created `{{bold-end}}` as `</b>`, then MWPFH won't parse `<b>foobar{{bold-end}}` correctly for the same reason. This often comes up in the context of tables—people like to construct table headers/footers from multiple templates but then use the raw syntax in the middle.

**Comment by Larivact** [comment]
I think `{{bold-end}}` would be a bad example since it doesn't make any sense.
Can you give me a simple example that actually makes sense?

**Comment by earwig** [comment]
https://en.wikipedia.org/wiki/Template:End

**Comment by Larivact** [comment]
I don't get it why wouldn't you just use `|}`?

**Comment by earwig** [comment]
Semantic clarity? I don't use it, but it exists.

**Comment by Larivact** [comment]
I fundamentally rewrote it. I think it's way more clear now.

**Comment by lahwaacz** [comment]
While you're at it, you could also add this (feel free to copy-paste):

- MediaWiki treats HTML comments in such a way that they can influence the surrounding elements (see https://github.com/earwig/mwparserfromhell/issues/55#issuecomment-49205052 for examples).

And a paragraph about language constructs depending on the MediaWiki configuration. In particular:

- Localized namespace names are unknown, so for example `[[File:...]]` links are treated as normal links (see #87 and #136).
- The suffixes for constructing [word-ending links](https://www.mediawiki.org/wiki/Help:Links#linktrail) are language-specific, mwparserfromhell does not handle them at all (see https://github.com/earwig/mwparserfromhell/issues/82).
- Anything that looks like an XML tag is parsed like a tag, although MediaWiki recognizes only a finite number of tags. This can currently confuse the parser a lot (see #102).

I only did a quick sweep through the existing issues, there might be more worth a mention.

**Comment by Larivact** [comment]
I renamed Caveats to Limitations since it's more descriptive and added a new "Configuration unawareness" section with the issues you suggested, only slightly reworded. I didn't add #55 since it isn't an inherent limitation (it could be fixed) and it isn't configuration-dependent.

**Comment by earwig** [comment]
Sorry, got a bit distracted and lost track of this. Thanks for helping out; I will accept this, make some changes, and update the web docs.

**Pull request merged**
