### PR TITLE
Issue #26 Use pure python on compilation failure

### PR DESCRIPTION
**Pull request by jayvdb**
Allow the compilation of the extension to fail, and switch
to pure python mode.

### CODE REVIEW

**Comment by earwig** [comment]
This is an excellent idea. Will merge after a review.

**Comment by earwig** [comment]
@jayvdb I'm a little confused here. If the build fails, why are we saving the extension files as package data? Wouldn't just ignoring them be sufficient?

**Comment by jayvdb** [comment]
This is working, but it is resulting in 'setup.py test' running twice.

@earwig , putting them in package_data means the installed package contains the same source files as the 'mwparserfromhell' directory in the source tree.

**Comment by jayvdb** [comment]
I've nearly got a fix for that; need to travel again.  Will upload tomorrow.

**Comment by earwig** [comment]
But what's the point of keeping the source files around if we couldn't build from them? They're not useful like that, and we don't keep the source files around if the build is successful, anyway. The parser shouldn't have a problem if those files are missing.

**Comment by jayvdb** [comment]
OK, I've removed the package_data part, and added WITHOUT_EXTENSION builds to travis.  The travis builds look like they are doing the right thing, but if you can spot something wrong I'll be happy to fix it.

**Pull request merged**
